In [219]:
import pandas as pd
import numpy as np
import sklearn as skl
import matplotlib.pyplot as plt
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from functools import reduce
import winsound

In [220]:
imdb = pd.read_csv("IMDb movies.csv")

c:\users\harsh\desktop\env\lib\site-packages\IPython\core\interactiveshell.py:3062: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [221]:
imdb.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,None,Alexander Black,...,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,None,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,$ 2250,NaN,NaN,NaN,7.0,7.0
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,...,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.8,188,NaN,NaN,NaN,NaN,5.0,2.0
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,...,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,$ 45000,NaN,NaN,NaN,25.0,3.0
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",...,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0

In [222]:
imdb.columns

Index(['imdb_title_id', 'title', 'original_title', 'year', 'date_published',
       'genre', 'duration', 'country', 'language', 'director', 'writer',
       'production_company', 'actors', 'description', 'avg_vote', 'votes',
       'budget', 'usa_gross_income', 'worlwide_gross_income', 'metascore',
       'reviews_from_users', 'reviews_from_critics'],
      dtype='object')

In [223]:
#remove values with no gross income data
imdb=imdb[imdb['usa_gross_income'].isna()==False]
imdb=imdb[imdb['worlwide_gross_income'].isna()==False]
imdb=imdb[imdb['budget'].isna()==False]
imdb.reset_index(drop=True, inplace=True)

In [224]:
#Remove dollar sign from revenue and budget
usa=[]
worldwide=[]
budget=[]
for index, row in imdb.iterrows():
    try:
        usa.append(row['usa_gross_income'].split('$ ')[1])
    except:
        usa.append(0)
    try:
        worldwide.append(row['worlwide_gross_income'].split('$ ')[1])
    except:
        worldwide.append(0)
        
    budget.append(row['budget'].split(' ')[1])

imdb['usa_gross_income']=[int(x) for x in usa]
imdb['worlwide_gross_income']=[int(x) for x in worldwide]
imdb['budget']=[int(x) for x in budget]

In [225]:
imdb

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0010323,Il gabinetto del dottor Caligari,Das Cabinet des Dr. Caligari,1920,1920-02-27,"Fantasy, Horror, Mystery",76,Germany,German,Robert Wiene,...,"Werner Krauss, Conrad Veidt, Friedrich Feher, ...","Hypnotist Dr. Caligari uses a somnambulist, Ce...",8.1,55601,18000,8811,8811,NaN,237.0,160.0
1,tt0012190,I quattro cavalieri dell'Apocalisse,The Four Horsemen of the Apocalypse,1921,1923-04-16,"Drama, Romance, War",150,USA,None,Rex Ingram,...,"Pomeroy Cannon, Josef Swickard, Bridgetta Clar...",An extended family split up in France and Germ...,7.2,3058,800000,9183673,9183673,NaN,45.0,16.0
2,tt0017136,Metropolis,Metropolis,1927,1928-10-01,"Drama, Sci-Fi",153,Germany,German,Fritz Lang,...,"Alfred Abel, Gustav Fröhlich, Rudolf Klein-Rog...",In a futuristic city sharply divided between t...,8.3,156076,6000000,1236166,1349711,98.0,495.0,208.0
3,tt0021749,Luci della città,City Lights,1931,1931-04-02,"Comedy, Drama, Romance",87,USA,English,Charles Chaplin,...,"Virginia Cherrill, Florence Lee, Harry Myers, ...","With the aid of a wealthy erratic tippler, a d...",8.5,162668,1500000,19181,46008,99.0,295.0,122.0
4,tt0027977,Tempi moderni,Modern Times,1936,1937-03-12,"Comedy, Drama, Family",87,USA,English,Charles Chaplin,...,"Charles Chaplin, Paulette Goddard, Henry Bergm...",The Tramp struggles to live in modern industri...,8.5,211250,1500000,163577,457688,96.0,307.0,115.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8121,tt9214832,Emma.,Emma.,2020,2020-03-27,"Comedy, Drama",124,UK,English,Autumn de Wilde,...,"Anya Taylor-Joy, Angus Imrie, Letty Thomas, Ge...","In 1800s England, a well meaning but selfish y...",6.7,19858,10000000,10055355,25659965,71.0,314.0,188.0
8122,tt9354944,Jexi,Jexi,2019,2019-10-11,"Comedy, Romance",84,"USA, Canada",English,"Jon Lucas, Scott Moore",...,"Adam Devine, Alexandra Shipp, Rose Byrne, Ron ...",A comedy about what can happen when you love y...,6.1,17038,5000000,6546159,9341824,39.0,234.0,42.0
8123,tt9426210,Weathering with You,Tenki no ko,2019,2019-10-14,"Animation, Drama, Family",112,"Japan, China",Japanese,Makoto Shinkai,...,"Kotaro Daigo, Nana Mori, Shun Oguri, Sei Hirai...",A high-school boy who has run away to Tokyo be...,7.6,16277,11100000,7798743,193176979,72.0,177.0,110.0
8124,tt9779516,Cosa mi lasci di te,I Still Believe,2020,2020-03-19,"Biography, Drama, Music",116,USA,English,"Andrew Erwin, Jon Erwin",...,"K.J. Apa, Britt Robertson, Nathan Parsons, Gar...",The true-life story of Christian music star Je...,6.5,6196,12000000,9868521,13681524,41.0,151.0,52.0
8125,tt9825006,Avant qu'on explose,Avant qu'on explose,2019,2019-02-28,Comedy,108,Canada,French,Rémi St-Michel,...,"Étienne Galloy, Amadou Madani Tall, William Mo...",The Third World War is on the horizon. Despite...,6.6,100,3850000,119894,119894,NaN,NaN,2.0

In [226]:
#split multiple items in column into a list of separate items
imdb['genre'] = (imdb['genre'].str.split(', '))
imdb['language'] = (imdb['language'].str.split(', '))
imdb['actors'] = (imdb['actors'].str.split(', '))
imdb['writer'] = (imdb['writer'].str.split(', '))
imdb['director'] = (imdb['director'].str.split(', '))

In [227]:
# perform sentiment analysis on description and title
des_scores=[]
title_scores=[]
analyzer = SentimentIntensityAnalyzer()
for x in imdb['description']:
    try:
        des_scores.append(analyzer.polarity_scores(x)['compound'])
    except TypeError:
        des_scores.append(0)

for x in imdb['title']:
    try:
        title_scores.append(analyzer.polarity_scores(x)['compound'])
    except TypeError:
        title_scores.append(0)
imdb['description_score']=des_scores
imdb['title']=title_scores
imdb.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics,description_score
0,tt0010323,0.0,Das Cabinet des Dr. Caligari,1920,1920-02-27,"[Fantasy, Horror, Mystery]",76,Germany,[German],[Robert Wiene],...,"Hypnotist Dr. Caligari uses a somnambulist, Ce...",8.1,55601,18000,8811,8811,NaN,237.0,160.0,-0.4215
1,tt0012190,0.0,The Four Horsemen of the Apocalypse,1921,1923-04-16,"[Drama, Romance, War]",150,USA,[None],[Rex Ingram],...,An extended family split up in France and Germ...,7.2,3058,800000,9183673,9183673,NaN,45.0,16.0,-0.7579
2,tt0017136,0.0,Metropolis,1927,1928-10-01,"[Drama, Sci-Fi]",153,Germany,[German],[Fritz Lang],...,In a futuristic city sharply divided between t...,8.3,156076,6000000,1236166,1349711,98.0,495.0,208.0,0.6369
3,tt0021749,0.0,City Lights,1931,1931-04-02,"[Comedy, Drama, Romance]",87,USA,[English],[Charles Chaplin],...,"With the aid of a wealthy erratic tippler, a d...",8.5,162668,1500000,19181,46008,99.0,295.0,122.0,0.7845
4,tt0027977,0.0,Modern Times,1936,1937-03-12,"[Comedy, Drama, Family]",87,USA,[English],[Charles Chaplin],...,The Tramp struggles to live in modern industri...,8.5,211250,1500000,163577,457688,96.0,307.0,115.0,0.0516

In [228]:
#get dummy variables for categories that need them
df = pd.get_dummies(imdb['genre'].apply(pd.Series).stack()).sum(level=0)
df2 = pd.get_dummies(imdb['language'].apply(pd.Series).stack()).sum(level=0)
df3 = pd.get_dummies(imdb['director'].apply(pd.Series).stack()).sum(level=0)
df4 = pd.get_dummies(imdb['writer'].apply(pd.Series).stack()).sum(level=0)

In [229]:
df = df.add_prefix('genre_')
df2 = df2.add_prefix('langauge_')
df3 = df3.add_prefix('director_')
df4 = df4.add_prefix('writer_')

In [230]:
#add similar column for merging
df['imdb_title_id']=imdb['imdb_title_id']
df2['imdb_title_id']=imdb['imdb_title_id']
df3['imdb_title_id']=imdb['imdb_title_id']
df4['imdb_title_id']=imdb['imdb_title_id']

In [231]:
#merge all dataframes into one
dfs = [imdb,df,df2,df3,df4]
df_final = reduce(lambda left,right: pd.merge(left,right,on='imdb_title_id'), dfs)

In [232]:
df_final.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,writer_Zoë Lund,writer_Àlex Pastor,writer_Álex de la Iglesia,writer_Álvaro Rodríguez,writer_Élie Chouraqui,writer_Émile Gaudreault,writer_Émile Zola,writer_Éric Rohmer,writer_Éric Tessier,writer_Éric Toledano
0,tt0010323,0.0,Das Cabinet des Dr. Caligari,1920,1920-02-27,"[Fantasy, Horror, Mystery]",76,Germany,[German],[Robert Wiene],...,0,0,0,0,0,0,0,0,0,0
1,tt0012190,0.0,The Four Horsemen of the Apocalypse,1921,1923-04-16,"[Drama, Romance, War]",150,USA,[None],[Rex Ingram],...,0,0,0,0,0,0,0,0,0,0
2,tt0017136,0.0,Metropolis,1927,1928-10-01,"[Drama, Sci-Fi]",153,Germany,[German],[Fritz Lang],...,0,0,0,0,0,0,0,0,0,0
3,tt0021749,0.0,City Lights,1931,1931-04-02,"[Comedy, Drama, Romance]",87,USA,[English],[Charles Chaplin],...,0,0,0,0,0,0,0,0,0,0
4,tt0027977,0.0,Modern Times,1936,1937-03-12,"[Comedy, Drama, Family]",87,USA,[English],[Charles Chaplin],...,0,0,0,0,0,0,0,0,0,0

In [233]:
# get a binary column to represent whether a movie was able to recoup its production costs
profitable = []
for index, row in df_final.iterrows():
    if row['worlwide_gross_income']>row['budget']:
        profitable.append(1)
    else:
        profitable.append(0)
df_final['profitable']=profitable

In [234]:
df_final.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,writer_Àlex Pastor,writer_Álex de la Iglesia,writer_Álvaro Rodríguez,writer_Élie Chouraqui,writer_Émile Gaudreault,writer_Émile Zola,writer_Éric Rohmer,writer_Éric Tessier,writer_Éric Toledano,profitable
0,tt0010323,0.0,Das Cabinet des Dr. Caligari,1920,1920-02-27,"[Fantasy, Horror, Mystery]",76,Germany,[German],[Robert Wiene],...,0,0,0,0,0,0,0,0,0,0
1,tt0012190,0.0,The Four Horsemen of the Apocalypse,1921,1923-04-16,"[Drama, Romance, War]",150,USA,[None],[Rex Ingram],...,0,0,0,0,0,0,0,0,0,1
2,tt0017136,0.0,Metropolis,1927,1928-10-01,"[Drama, Sci-Fi]",153,Germany,[German],[Fritz Lang],...,0,0,0,0,0,0,0,0,0,0
3,tt0021749,0.0,City Lights,1931,1931-04-02,"[Comedy, Drama, Romance]",87,USA,[English],[Charles Chaplin],...,0,0,0,0,0,0,0,0,0,0
4,tt0027977,0.0,Modern Times,1936,1937-03-12,"[Comedy, Drama, Family]",87,USA,[English],[Charles Chaplin],...,0,0,0,0,0,0,0,0,0,0

In [235]:
#get the feature and label sets
#remove all the features that wouldn't be known until after a movie is produced
X = df_final.drop(['imdb_title_id','title','original_title','date_published',
                   'genre', 'duration', 'country', 'language', 'director', 'writer',
                   'production_company', 'actors', 'description', 'avg_vote', 'votes',
                   'usa_gross_income', 'worlwide_gross_income', 'metascore','reviews_from_users', 
                   'reviews_from_critics', 'description_score'],axis=1)
y = df_final['profitable']

In [236]:
corlist=pd.DataFrame(X.corrwith(y),columns=['coor'])

In [237]:
corlist.reset_index(inplace=True)

In [238]:
df1 = corlist[corlist['coor']!=0]

In [239]:
X = X[df1['index']]
X.drop('profitable',axis=1,inplace=True)

In [240]:
X.dropna(inplace=True)

In [242]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

classifier = RandomForestClassifier()
classifier.fit(X_train,y_train)

model = SelectFromModel(classifier, prefit=True)
X = model.transform(X)

In [243]:
# generate more samples from the data to balance out binary outcomes
from imblearn.over_sampling import SMOTE

oversample = SMOTE()
X, y = oversample.fit_resample(X, y)

In [244]:
#get a training and test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.5, random_state=0)

In [245]:
# standardize the data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_val = sc.transform(X_val)
X_test = sc.transform(X_test)

In [246]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [247]:
# predict values using X test and the new model
y_pred = classifier.predict(X_val)

In [248]:
#print the confusion matrix as well as multiple scores to evaluate the model
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, f1_score 
cm = confusion_matrix(y_val, y_pred)
print(cm)
print('Accuracy: ' + str(accuracy_score(y_val, y_pred)))
print('AUC: ' + str(roc_auc_score(y_val, y_pred)))
print('F1 Score: ' + str(f1_score(y_val, y_pred)))

[[722 148]
 [519 427]]
Accuracy: 0.6327092511013216
AUC: 0.6406296323297126
F1 Score: 0.5614727153188692

In [249]:
#use grid search cv to run multiple random forest classifier models to find best hyperparameters
from sklearn.model_selection  import GridSearchCV

param_grid = { 
    'n_estimators': [50, 100, 250],
    'max_features': ['auto','sqrt']
}

CV_rfc = GridSearchCV(estimator=classifier, param_grid=param_grid, cv= 5,n_jobs=-1)
CV_rfc.fit(X_val, y_val)
print(CV_rfc.best_estimator_)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=250,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [250]:
winsound.Beep(440,250)

In [251]:
# predict values using X test and the new model
y_pred = CV_rfc.best_estimator_.predict(X_test)

In [252]:
#print the confusion matrix as well as multiple scores to evaluate the model
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, f1_score 
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))
print('AUC: ' + str(roc_auc_score(y_test, y_pred)))
print('F1 Score: ' + str(f1_score(y_test, y_pred)))

[[667 264]
 [413 472]]
Accuracy: 0.6272026431718062
AUC: 0.6248836376655925
F1 Score: 0.5823565700185072

In [256]:
# perform multiple random permutations to find p-value 
from sklearn.model_selection import permutation_test_score
from sklearn.model_selection import StratifiedKFold

clf = CV_rfc.best_estimator_
cv = StratifiedKFold(2, shuffle=True, random_state=0)

score_orig, perm_scores_orig, pvalue_orig = permutation_test_score(
    clf, X_test, y_test, scoring="accuracy", cv=cv, n_permutations=100)

In [257]:
pvalue_orig

0.009900990099009901

In [258]:
winsound.Beep(440,250)